### PR TITLE
Fix maximum comment length

### PR DESCRIPTION
**Pull request by smokedlinq**
This handle scenarios when the plan+diff or any combination exceeds the 65k limit such as the #68 issue. It will truncate the comment and place a note that it was too large to comment and outputs the original content to the log to the action.

### CODE REVIEW

**Comment by ahmadnassri** [comment]
brilliant, thank you.

will review and merge today

**Comment by smokedlinq** [comment]
@ahmadnassri checking in, anything else needed that I can help with?

**Comment by smokedlinq** [comment]
@ahmadnassri just checking in if there is anything I can do to move this along?

**Comment by smokedlinq** [comment]
@ahmadnassri any chance getting this merged?

**Comment by smokedlinq** [comment]
@ahmadnassri are you alright and willing to accept this or should we fork this action if you aren't maintaining this anymore?

**Comment by smokedlinq** [comment]
@ahmadnassri any chance on getting this merged, as well as the node16->node20 update?

**Comment by ahmadnassri** [comment]
@smokedlinq apologies for the delay, merged.

**Pull request merged**
